language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r REQUIREMENTS
  - python setup.py install

script:
  - python setup.py test

deploy:
  provider: pypi
  user: scottphilip
  password:
    secure: "DTN+xYwu91n9Wsf10L3iYBOpvZRj+/ZiXh+/6AbtNH31NshC4eJRlYl3zPzzDTFFe05r1/3tflKY7Mh/4Fvh5xrKT4Y9V8XQGwoY1aeoPKaBdaLxfZftHeQsPZLB3ouufcfaVgMckPLdBCr5wXZ2Bh23TnRKZeLhnEGLI/EyRbesQ8HyOnctxYR93o7AKFIuZXvlsVOs/MV3VDcTDJf6Rp3x51K+IKzEhhJcczjw045WS3v31ZZzDZ+j1/BUGIpn4B+XC+Gm/vGaUZbK8cW1ulw6uToMY98kU0pNoRx4cg+klvIpzUetwZ/oXpfnBx4slGqwEjoAl0pcks7SxDYYpwTc8tFPl2+HAtWYAMu2JgOsToKxQqfSxC907IhmkKXXYHQiiR8KqOdvB7lEiiqSu0QQ/v7sMfhzAZB6eSBUFWyBmJ27g1D6BMU9WpJ8yGqeyEBginZNvU0kjhUGTajgaIj9VWpHokEVI49X0XO5czshT0fa7OfEQgoErZfmnfokoDW5+D+4hVbzsFRJnID6XSrSyIThKpaghVUhnmYUnjZ+/LOvudgMzqIRQNdASfjk+i2UwVv8fcG+Klew4vZ7Qe4/YQ6vS/WnpwDy44PiEemIaQoA5GpWROI8T0T2Zp6NGv6Pznn0VbgC6J9L2enpip7gqdfKFLzCp0dzXcprI5o="
  on:
    all_branches: true
