language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_8b67e2a67e3b_key -iv $encrypted_8b67e2a67e3b_iv
  -in TestVariables.json.enc -out TestVariables.json -d
install:
- pip install -r REQUIREMENTS.txt
- python setup.py install
script:
- pip install Pygments
- pip install docutils
- python setup.py test
- python setup.py check --restructuredtext
after_success:
- chmod +x COPYLOGS.sh
- "./COPYLOGS.sh"
after_failure:
- chmod +x COPYLOGS.sh
- "./COPYLOGS.sh"
env:
  global:
  - IS_DEBUG=True
  - secure: RfLhjDXjG6Fak8rCa9KIIhsGMjQzgYL3TTpoSGEWZdfHUFt1R/XDf2ddbpcldwdYlJsTxkl5lCNnUeW445o2FTZNVCifZb113vKE/q5h25jgsKfVa+Ugv90rgQaX2YygVGY/wRPdIPiVDSpz4hi1OQ8eWAXQWjBNpYCs44DjZPHApI738CAU486LYPaZDQ1GXWnrYUjauVxCupLabW90pUd5lgH28zHe8pX+V0EMgt80nBDnwIBgGyu3uK2fV6v20TLptfNEOOxUlaIIJcHE/yp7H3RgvSsEeSmbfIfcDsMrVmO8AhH/jVFmF9vfp9Xy1J31t52OBLrP4MGsu2Fa33EdHfi9UVGSep7UOZDKFd/UXzGJaDzsnNGojQ/4nsNkvStHt7aM1LVH5JTrcQL1SY+VdWtLEoS62ll8p1Al8dMDmtbv6Tfxp0cv05i/UA0SCB8kK5offDGgls5sP3zo/0Ek4AIwFgKKUNHtt3DgWKtkz5W23p1BSH8mNIL+GltrA0nf/7fiZ3lH5Nmyg0677QhQpRfaudtSqUNlLloWjwBEtBWlQ0UgT7W48zpkAVcm6NOvYfeM6xvgvEa3XaA09H+AEnmXgEwPkTB8rmzcSIIlYFN8pc1ImP/X2WFDOgfxHSuNAaeAq1iJGMOoyPwOzHG/GbHDh4CXyvcgs+UdSuc=
deploy:
  provider: pypi
  user: scottphilip
  password:
    secure: kNehYsZo8LUScLVlIW3PKM9jrlTvGVnu+MpRgTfnK4J69YsdOmvB4i7bTUc+fpF/N875+hdOe80XgQBXG15S99F0v4V46gaEuHhDx+I8KuLeEmy3wENkPh5HeNjj5aAOtAD6t7J4tN72ZTSXmIfU5oBaf+17MBoW/MuCeRrATVuoWGdnOmEXLuw02YXhlns+NiPshC/qPQdthUltS5roqHTEzeX2d320UUK6lgRSVNeMy7OTGTdjO7zXCw+O+3qVfhVTlLjOsvmV/KaqiYzRkEyvqA3RvWejqPBVY8+9q/rgujZarjJsdJVDjhVHPUHDKcey2idoF2M19bpxncWNPQH3NN3vTzfwrGRBbL08S5yjNtN7j1u2PopvyQkQzmStp2rXro02xOnoRqUCbCIqcWBhCz3pWu5pxIRIKCyEfZR8+9t+6vJiPeRa5Ka+3B/wPIVMmA6xUSAWKbCLwg4guGJEeG8MCJZXy3vawOXhMnus8O8x4rFbuXeO2NUikOPke+KrkRQeub41idhTZqwrRledh5+2YJlxJ8Rxv0L+F1iSjp/NanltZotU7TEhOl1GG3JcP7SGwzz5mUpGMz30ro9rTLsmdTqTKfoXJuIunqzWkOytqBzA8TozGarak9rmIDbPTAmXYao18rl6lISJq2MDrgu0wfJRwZbQPRkisSw=
  on:
    all_branches: true
