language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_8b67e2a67e3b_key -iv $encrypted_8b67e2a67e3b_iv
  -in TestVariables.json.enc -out TestVariables.json -d
install:
- pip install -r REQUIREMENTS.txt
- python setup.py install
script:
- pip install Pygments
- pip install docutils
- python setup.py test
- python setup.py check --strict --restructuredtext
env:
  global:
  - IS_DEBUG=True
deploy:
  provider: pypi
  user: scottphilip
  password:
    secure: kNehYsZo8LUScLVlIW3PKM9jrlTvGVnu+MpRgTfnK4J69YsdOmvB4i7bTUc+fpF/N875+hdOe80XgQBXG15S99F0v4V46gaEuHhDx+I8KuLeEmy3wENkPh5HeNjj5aAOtAD6t7J4tN72ZTSXmIfU5oBaf+17MBoW/MuCeRrATVuoWGdnOmEXLuw02YXhlns+NiPshC/qPQdthUltS5roqHTEzeX2d320UUK6lgRSVNeMy7OTGTdjO7zXCw+O+3qVfhVTlLjOsvmV/KaqiYzRkEyvqA3RvWejqPBVY8+9q/rgujZarjJsdJVDjhVHPUHDKcey2idoF2M19bpxncWNPQH3NN3vTzfwrGRBbL08S5yjNtN7j1u2PopvyQkQzmStp2rXro02xOnoRqUCbCIqcWBhCz3pWu5pxIRIKCyEfZR8+9t+6vJiPeRa5Ka+3B/wPIVMmA6xUSAWKbCLwg4guGJEeG8MCJZXy3vawOXhMnus8O8x4rFbuXeO2NUikOPke+KrkRQeub41idhTZqwrRledh5+2YJlxJ8Rxv0L+F1iSjp/NanltZotU7TEhOl1GG3JcP7SGwzz5mUpGMz30ro9rTLsmdTqTKfoXJuIunqzWkOytqBzA8TozGarak9rmIDbPTAmXYao18rl6lISJq2MDrgu0wfJRwZbQPRkisSw=
  on:
    all_branches: true
