language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_8b67e2a67e3b_key -iv $encrypted_8b67e2a67e3b_iv
  -in TestVariables.json.enc -out TestVariables.json -d
install:
- pip install -r REQUIREMENTS.txt
- python setup.py install
script:
- pip install Pygments
- pip install docutils
- python setup.py test
- python setup.py check --restructuredtext
after_success:
- chmod +x COPYLOGS.sh
- "./COPYLOGS.sh"
after_failure:
- chmod +x COPYLOGS.sh
- "./COPYLOGS.sh"
env:
  global:
  - IS_DEBUG=True
  - secure: AySuW2Ra9rlgOC1B+HsTuEpEPDvDgyUE0TaPJcF2rYAzXqnWPn104wBjverzfDDyTABPIj3C41hBZcp8x1ZdxrBl6fkq92F9k08yqoPoshtTy7y2MQO5o07/v9+Sm+/VR9d5td0WyBYMEF07g60ucB0H4sTO2VNVDxSyWSyB0vo+c1UaccJnJPmkel8vddVSOG8KMlQBkqBG9tA4/JiYnxJqy45R4BUZURBEIDkdWHlHNO60zijzWoblPqTqIt468BB7FZc9iqy0CewmAq/RR4f6w12JC3b5r0l26GJORrLgtRBvu50VRNfzxqeXA1pTdfWgMZnEFfxcLI2ZrgysyvUScwThz/0zRbjSnnPnqdn7nxLj9LCCLLrYNp8ue4Q2RV/g9xvT8PtIxeKdG4jxTCPlx3WiT9IZAuAg1UIQIEWJtASO2ZO1ObCfqefYr4/OiHiVl2fkivas4fMnot5y5p1PitA/Qr5UL+L7k5E4Xl95nLu0ETIwAyMchre4u9JbUiCVakyTCrnqxqBtc8BPob6GQdbx2+1ZKENO9dPOZ2pRNmuGm+ZKYW3Y/nNqHksqs2q09sUijOSDDYNkhSETjNvLZJyov9H41yODL369dXKX20V58JZxlEdYd5W6B7uwAde+UEowOxHg1Y0Q6Z0O3OEK07J/No+0LZBN07L3ee0=
  - secure: OaLy2KiOvF0hQiw/R/wCirwS4cFQOR1pk/gNv3G239hZr3zLt8NkWnoFan5KuBHsEXLi3n6sTsPNRcg+tBoF8q8BKXCyaPprz3AUYAP0P0DDvhL2tkCdC3UEantnpsfHXifJNmJbJKdmf1hgIN3j+Km5wR5S+OYG9qHbfMAD3uUGST/6iWeEE8lw98IujbD3Cgmu/zfKpmVp+R7of/p1Be+ALiDhi2w7U5GK95LoT+Qxo7O/k23h1WIxWdsrH+znevykkPF2V8n75FJA590amGBocdAunZXZrVyiib4sWTcpv6/LWU0qAI4T5gQ3GJBDQPrGm2LODXwuUoCtPP+gviWKSMlMw3QTgF3E1lfM47vjplbuc9si/5LEG7shQJlJcwQY1IE0O5z86U2sK8xx60waNxJhvjDHMzaA3sTf2eQXEq6LNQMgkt7SAEbvbaLFjb28XrMm/uXhBpN9BTA++jL4qt/rnu5YrsCjDZuQ2ly5te64rIH4b2ZBAVj9m1Pl1HIuZHW/I2/rkrkCMDGVkjg+4qOvm8VivQo6iPH0DpW4xRTjDk8lkfARPCTSsQFOLCOKxPpJVhh8hBXM+uz7jJqGKhwrJxZqd8oV0Z6i6IALuH/DX8nyEPtg32ZC7QoAnE24t6uyEkBDFeOLEjoK+DAVpq8hlMU4lq0eB6tKnUY=
deploy:
  provider: pypi
  user: scottphilip
  password:
    secure: kNehYsZo8LUScLVlIW3PKM9jrlTvGVnu+MpRgTfnK4J69YsdOmvB4i7bTUc+fpF/N875+hdOe80XgQBXG15S99F0v4V46gaEuHhDx+I8KuLeEmy3wENkPh5HeNjj5aAOtAD6t7J4tN72ZTSXmIfU5oBaf+17MBoW/MuCeRrATVuoWGdnOmEXLuw02YXhlns+NiPshC/qPQdthUltS5roqHTEzeX2d320UUK6lgRSVNeMy7OTGTdjO7zXCw+O+3qVfhVTlLjOsvmV/KaqiYzRkEyvqA3RvWejqPBVY8+9q/rgujZarjJsdJVDjhVHPUHDKcey2idoF2M19bpxncWNPQH3NN3vTzfwrGRBbL08S5yjNtN7j1u2PopvyQkQzmStp2rXro02xOnoRqUCbCIqcWBhCz3pWu5pxIRIKCyEfZR8+9t+6vJiPeRa5Ka+3B/wPIVMmA6xUSAWKbCLwg4guGJEeG8MCJZXy3vawOXhMnus8O8x4rFbuXeO2NUikOPke+KrkRQeub41idhTZqwrRledh5+2YJlxJ8Rxv0L+F1iSjp/NanltZotU7TEhOl1GG3JcP7SGwzz5mUpGMz30ro9rTLsmdTqTKfoXJuIunqzWkOytqBzA8TozGarak9rmIDbPTAmXYao18rl6lISJq2MDrgu0wfJRwZbQPRkisSw=
  on:
    all_branches: true
